galaxy_info:
  author: Raul Becker
  description: wmanme
  license: "MIT"
  min_ansible_version: "2.1"
  platforms:
    - name: "Debian"
      versions:
        - "bullseye"
        - "bookworm"
    - name: "FreeBSD"
      versions:
        - "all"
  galaxy_tags: []
dependencies:
  - { role: handlers }
